import { Lightbulb } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./ui/accordion";
import type { SuggestionCategory } from "@/types";

interface AiSuggestionsProps {
    suggestions: SuggestionCategory[];
}

export function AiSuggestions({ suggestions = [] }: AiSuggestionsProps) {
    if (!suggestions || suggestions.length === 0) {
        return (
             <Card className="bg-gradient-to-br from-primary/10 via-transparent to-transparent border-primary/20 shadow-lg hover:shadow-primary/20 transition-shadow">
                <CardHeader className="flex flex-row items-center gap-4">
                    <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                        <Lightbulb className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                        <CardTitle>AI-Powered Suggestions</CardTitle>
                        <CardDescription>Actionable insights to improve your business.</CardDescription>
                    </div>
                </CardHeader>
                <CardContent>
                    <div className="flex h-full min-h-[150px] items-center justify-center rounded-lg border-2 border-dashed border-border/50 bg-background/30">
                        <p className="text-muted-foreground">No specific suggestions generated by AI.</p>
                    </div>
                </CardContent>
            </Card>
        )
    }

    return (
        <Card className="bg-gradient-to-br from-primary/10 via-transparent to-transparent border-primary/20 shadow-lg hover:shadow-primary/20 transition-shadow">
            <CardHeader className="flex flex-row items-center gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                    <Lightbulb className="h-6 w-6 text-primary" />
                </div>
                <div>
                    <CardTitle>AI-Powered Suggestions</CardTitle>
                    <CardDescription>Actionable insights to improve your business.</CardDescription>
                </div>
            </CardHeader>
            <CardContent>
                <Accordion type="multiple" defaultValue={suggestions.map(c => c.title)}>
                    {suggestions.map((category, index) => (
                        <AccordionItem key={index} value={category.title}>
                            <AccordionTrigger className="text-lg font-semibold text-primary/90 hover:text-primary">
                                {category.title}
                            </AccordionTrigger>
                            <AccordionContent>
                                <ul className="space-y-3 pl-5 pt-2">
                                    {category.points.map((point, pIndex) => (
                                        <li key={pIndex} className="relative pl-4 text-base leading-relaxed">
                                            <span className="absolute left-0 top-1.5 h-1.5 w-1.5 rounded-full bg-primary/70"></span>
                                            {point}
                                        </li>
                                    ))}
                                </ul>
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            </CardContent>
        </Card>
    );
}
