
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
    const [lastUpdated, setLastUpdated] = useState('');

    useEffect(() => {
        setLastUpdated(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));
    }, []);

    const sections = [
        {
            title: "1. Acceptance of Terms",
            content: "By accessing or using RENASIS (the \"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). If you disagree with any part of the terms, then you may not access the Service."
        },
        {
            title: "2. Description of Service",
            content: "RENASIS is an open-access web application that provides AI-driven analysis of customer reviews using your own Google AI API keys. The Service allows users to upload files containing review data and receive analytics, including sentiment analysis, issue identification, and business suggestions. You must provide your own valid Google AI API key to use the analysis features."
        },
        {
            title: "3. User-Uploaded Content and API Keys",
            content: "You are solely responsible for the content you upload and the API keys you provide. You represent and warrant that you have all necessary rights to upload the content and use the API keys, and that neither violates any third-party rights or applicable laws. We do not store your uploaded files, API keys, or the data contained within them. API keys are stored locally on your device and never transmitted to our servers."
        },
        {
            title: "4. API Key Usage and Costs",
            content: "You are responsible for all costs associated with your Google AI API key usage. RENASIS does not control or monitor your API usage or associated charges. You agree to comply with Google's terms of service for their AI services. Rate limits and usage restrictions are determined by your API key's configuration with Google."
        },
        {
            title: "5. No Warranty",
            content: "The Service is provided on an \"AS IS\" and \"AS AVAILABLE\" basis. RENASIS makes no warranties, express or implied, regarding the accuracy, reliability, or completeness of the analytics provided. The insights generated by AI are for informational purposes only and should not be considered as professional advice."
        },
        {
            title: "6. Limitation of Liability",
            content: "In no event shall RENASIS, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service."
        },
        {
            title: "7. Changes to Terms",
            content: "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page."
        },
        {
            title: "8. Contact Us",
            content: "If you have any questions about these Terms, please contact us at support@reviewinsights.ai."
        }
    ];

    return (
        <div className="bg-background">
            <div className="container mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
                <div className="space-y-10">
                    <div className="relative text-center">
                        <Link href="/" passHref>
                            <Button variant="outline" className="absolute left-0 top-1/2 -translate-y-1/2">
                                <ArrowLeft className="mr-2" />
                                Back to Home
                            </Button>
                        </Link>
                        <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl">Terms of Service</h1>
                        {lastUpdated && <p className="mt-4 text-lg text-muted-foreground">Last updated: {lastUpdated}</p>}
                    </div>
                    
                    <div className="space-y-8 rounded-lg border bg-card p-6 text-card-foreground shadow-sm md:p-10">
                        {sections.map((section, index) => (
                            <section key={index}>
                                <h2 className="text-2xl font-bold text-primary">{section.title}</h2>
                                <p className="mt-2 leading-relaxed text-muted-foreground">{section.content}</p>
                            </section>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}
